---
title: "Model 2"
author: "Mara Elali"
output: pdf_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tensorflow)
library(keras)
library(dplyr)  
library(rsample)
```


```{r}
#Load the dataset
radData <- read.csv("radiomics_completedata.csv")
str(radData)
#check first entries
head(radData)
#null and missing values
na.omit(radData)
#normalize
rad <- radData %>% mutate_if(is.ordered, factor, ordered = FALSE)
```
```{r}
#Split data into training (80%) and testing (20%)
set.seed(24)
rad_split <- initial_split(rad, prop = 0.8, strata = "Failure.binary")
rad_train <- training(rad_split)
rad_test <- testing(rad_split)

#checking sizes...
str(rad_train)
str(rad_test)

```

```{r}
#Identify features
Y <- "Failure.binary"
X <- setdiff(names(rad_train), Y)

#Convert to categorical
Y <- rad$Failure.binary
Y <- to_categorical(Y, 180)

#Convert to matrix
#rad_mat <- as.matrix(rad)
#class(rad_mat)
```


```{r}
#Create model
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "sigmoid", input_shape = ncol(X)) %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 128, activation = "sigmoid") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 128, activation = "sigmoid") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 64, activation = "sigmoid") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 64, activation = "sigmoid") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 2, activation = "softmax")
  
```

```{r}
#backpropagate
model %>% compile(
  loss = "categorical_crossentropy",
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
```

```{r}
#compile
model %>% compile(
  loss = "catrgorical_crossentropy",
  optimizer = optimizer_adam(),
  metrics = c("accuracy")
)
```

```{r}

history <- model %>% 
  fit(x = X,  
      y = Y, 
      epochs = 10, 
      batch_size = 128, 
      validation_split = 0.15)

#model evaluation
model %>%
  evaluate(X, Y)

#model prediction
model %>%
  predict_classes(X)

history <- model %>%
  fit(
  x = X,
  y = Y,
  epochs = 10,
  batch_size = 128,
  validation_split = 0.15,
  verbose = FALSE
  )
```

```{r}
#evaluate
model %>%
  evaluate(rad_test)

#predict
model %>%
  predict_classes(rad_test)
```
