---
title: "Model 1"
author: "Mara Elali"
output: pdf_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(glmnet)
library(pROC)   
library(dplyr)
library(ggplot2)
library(rsample)
library(recipes)
library(vip)
library(keras)
library(randomForest)
library(h2o)
library(randomForest)
library(caret)
```


```{r}
#Load the dataset
radData <- read.csv("radiomics_completedata.csv")
str(radData)
#check first entries
head(radData)
#null and missing values
na.omit(radData)
#normalize
rad <- radData %>% mutate_if(is.ordered, factor, ordered = FALSE)
```

```{r}
set.seed(123)
trainIndex <- createDataPartition(rad$Failure.binary, p = 0.8, list = FALSE)
rad_train <- rad[trainIndex, ]
rad_test <- rad[-trainIndex, ]

```

```{r}
#data correlation
num_rad <- sapply(rad, is.numeric)
corrMat <- cor(rad[, num_rad])
corrMat
```

```{r}
y <- as.data.frame(rad$Failure.binary)
Y <- to_categorical(Y, 197)
```

```{r}
# Fit logistic regression model
class(Failure.binary ~ .)

set.seed(24)
lrModel <- train(y, data = rad_train, method = "glm", family = "binomial")
lrModel
```

```{r}
# Fit random forest model
set.seed(24)
rfModel <- train(Failure.binary ~ ., data = rad_train, method = "rf", ntree = 50)
rfModel
```


```{r}
# Fit SVM model
set.seed(24)
svmModel <- train(Failure.binary ~ ., data = rad_train, method = "svmRadial")
svmModel
```

```{r}
summary(
  resamples(
    list(
      model1 = lrModel,
      model2 = rfModel,
      model3 = svmModel
    )
  )
)$statistics$accuracy
```



```{r}
# Create ensemble model
set.seed(24)
ensembleModel <- caretStack(
  all.models = list(lrModel, rfModel, svmModel),
  method = "glm"
)
```


```{r}
#train stacked model
get_rmse <- function(model) {
  results <- h2o.performance(model, newdata = test.h2o)
  results@metrics$RMSE
}
list(rad_glm, rad_gbm, rad_rf) %>%
  purrr::map_dbl(get_rmse)

ensemble <- h2o.stackedEnsemble(
  x = X, y = Y, training_frame = train.h2o, base_models = list(rad_gbm, rad_glm, rad_rf)
)

h2o.performance(ensemble, newdata = test.h2o)@metrics$RMSE

```





vip(cv_model3, num_features = 20)


##top 20 most important features
imp <- varImp(knn_)
##variable iportance plot
vip::vip(xgb.fit.final)

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
