---
title: "Model 1"
output: pdf_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(keras)
library(caret)
library(rsample)   
library(recipes)   
library(h2o)  
library(dplyr)
library(ggplot2)
library(vip)
```


```{r}
#Load the dataset
radData <- read.csv("radiomics_completedata.csv")
str(radData)
#check first entries
head(radData)
#null and missing values
na.omit(radData)
#normalize
rad <- radData %>% mutate_if(is.ordered, factor, ordered = FALSE)
```

```{r}
#Split data into training (80%) and testing (20%)
set.seed(24)
rad_split <- initial_split(rad, prop = 0.8, strata = "Failure.binary")
rad_train <- training(rad_split)
rad_test <- testing(rad_split)
```


#```{r}
#data correlation
round(cor(X, Y),
  digits = 2 # rounded to 2 decimals
)
#```

```{r}
#train and validate glm
rad_glm <- h2o.glm(
  x = X, y = Y, training_frame = train.h2o, alpha = 0.1,
  remove_collinear_columns = TRUE, nfolds = 10, fold_assignment = "Modulo",
  keep_cross_validation_predictions = TRUE, seed = 24
)
```


```{r}
#train and validate rf
rad_rf <- h2o.randomForest(
  x = X, y = Y, training_frame = train.h2o, ntrees = 1000, mtries = 20,
  max_depth = 30, min_rows = 1, sample_rate =  0.8, nfolds = 10,
  fold_assignment = "Modulo", keep_cross_validation_predictions = TRUE,
  seed = 24, stopping_rounds = 50, stopping_metric = "RMSE",
  stopping_tolerance = 0
)
```

```{r}
#train and validate gbm
rad_gbm <- h2o.gbm(
  x = X, y = Y, training_frame = train.h2o, ntrees = 5000, learn_rate = 0.01,
  max_depth = 7, min_rows = 5, sample_rate = 0.8, nfolds = 10,
  fold_assignment = "Modulo", keep_cross_validation_predictions = TRUE,
  seed = 24, stopping_rounds = 50, stopping_metric = "RMSE",
  stopping_tolerance = 0
)
```
```{r}
summary(
  resamples(
    list(
      model1 = rad_glm,
      model2 = rad_rf,
      model3 = rad_gbm
    )
  )
)
```

```{r}
#train stacked model
get_rmse <- function(model) {
  results <- h2o.performance(model, newdata = test.h2o)
  results@metrics$RMSE
}
list(rad_glm, rad_gbm, rad_rf) %>%
  purrr::map_dbl(get_rmse)

ensemble <- h2o.stackedEnsemble(
  x = X, y = Y, training_frame = train.h2o, base_models = list(rad_gbm, rad_glm, rad_rf)
)

h2o.performance(ensemble, newdata = test.h2o)@metrics$RMSE

```



```{r}
Y <- rad$Failure.binary
Y <- to_categorical(Y, 197)
```





##top 20 most important features
imp <- varImp(knn_)
##variable iportance plot
vip::vip(xgb.fit.final)

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
